# Generated by Django 4.1.5 on 2023-12-15 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('text', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('keys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.task')),
            ],
            options={
                'verbose_name': 'комментарии к отзывам',
                'verbose_name_plural': 'комментарии к отзывам',
            },
        ),
    ]
